package com.bsd.oms.process;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	
	private long taskId;

	private java.lang.Long id;

	private java.lang.String orderDate;

	private java.lang.Long productId;

	private java.lang.String productName;

	private java.lang.Integer quantity;

	private java.lang.Double unitPrice;

	private java.lang.Double discount;

	private java.lang.Double salePrice;

	private java.lang.Long customerId;

	private java.lang.Long deliveryAddressId;

	private java.lang.Boolean isPaymentReceived;

	private java.lang.Boolean isOrderPlaced;

	public OrderDetails() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(java.lang.String orderDate) {
		this.orderDate = orderDate;
	}

	public java.lang.Long getProductId() {
		return this.productId;
	}

	public void setProductId(java.lang.Long productId) {
		this.productId = productId;
	}

	public java.lang.String getProductName() {
		return this.productName;
	}

	public void setProductName(java.lang.String productName) {
		this.productName = productName;
	}

	public java.lang.Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(java.lang.Integer quantity) {
		this.quantity = quantity;
	}

	public java.lang.Double getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(java.lang.Double unitPrice) {
		this.unitPrice = unitPrice;
	}

	public java.lang.Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Double discount) {
		this.discount = discount;
	}

	public java.lang.Double getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(java.lang.Double salePrice) {
		this.salePrice = salePrice;
	}

	public java.lang.Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.Long customerId) {
		this.customerId = customerId;
	}

	public java.lang.Long getDeliveryAddressId() {
		return this.deliveryAddressId;
	}

	public void setDeliveryAddressId(java.lang.Long deliveryAddressId) {
		this.deliveryAddressId = deliveryAddressId;
	}

	public java.lang.Boolean getIsPaymentReceived() {
		return this.isPaymentReceived;
	}

	public void setIsPaymentReceived(java.lang.Boolean isPaymentReceived) {
		this.isPaymentReceived = isPaymentReceived;
	}

	public java.lang.Boolean getIsOrderPlaced() {
		return this.isOrderPlaced;
	}

	public void setIsOrderPlaced(java.lang.Boolean isOrderPlaced) {
		this.isOrderPlaced = isOrderPlaced;
	}

	public long getTaskId() {
		return taskId;
	}

	public void setTaskId(long taskId) {
		this.taskId = taskId;
	}

	public OrderDetails(java.lang.Long id, java.lang.String orderDate,
			java.lang.Long productId, java.lang.String productName,
			java.lang.Integer quantity, java.lang.Double unitPrice,
			java.lang.Double discount, java.lang.Double salePrice,
			java.lang.Long customerId, java.lang.Long deliveryAddressId,
			java.lang.Boolean isPaymentReceived, java.lang.Boolean isOrderPlaced) {
		this.id = id;
		this.orderDate = orderDate;
		this.productId = productId;
		this.productName = productName;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.discount = discount;
		this.salePrice = salePrice;
		this.customerId = customerId;
		this.deliveryAddressId = deliveryAddressId;
		this.isPaymentReceived = isPaymentReceived;
		this.isOrderPlaced = isOrderPlaced;
	}

	@Override
	public String toString() {
		return "OrderDetails [id=" + id + ", orderDate=" + orderDate
				+ ", productId=" + productId + ", productName=" + productName
				+ ", quantity=" + quantity + ", unitPrice=" + unitPrice
				+ ", discount=" + discount + ", salePrice=" + salePrice
				+ ", customerId=" + customerId + ", deliveryAddressId="
				+ deliveryAddressId + ", isPaymentReceived="
				+ isPaymentReceived + ", isOrderPlaced=" + isOrderPlaced + "]";
	}

}